<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\{ProjectCategory,Project,ProjectMedia,PostCategory,Post,Career};
class DatabaseSeeder extends Seeder { public function run(): void {
 $pc=[]; foreach(['Residential','Commercial','Industrial','Hospitality'] as $name){$pc[$name]=ProjectCategory::create(['name'=>$name,'slug'=>str($name)->slug()]);}
 $images=['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=85'];
 $projects=[['Central Residence','Residential','Da Nang','1,240 m²','2026','Reinforced Concrete','14 months'],['Harbour Office Campus','Commercial','Da Nang','8,600 m²','2025','Steel + RC','18 months'],['North Logistics Hub','Industrial','Quang Nam','21,000 m²','2026','Pre-engineered Steel','16 months'],['Seaside Boutique Hotel','Hospitality','Hoi An','6,450 m²','2025','RC Frame','20 months'],['Courtyard House','Residential','Hue','620 m²','2024','RC Frame','11 months'],['Civic Innovation Center','Commercial','Da Nang','12,500 m²','2024','RC + Steel','22 months']];
 foreach($projects as $i=>$p){$x=Project::create(['category_id'=>$pc[$p[1]]->id,'title'=>$p[0],'slug'=>str($p[0])->slug(),'client_name'=>'Private Client','location'=>$p[2],'area_sqm'=>$p[3],'year'=>$p[4],'structural_type'=>$p[5],'timeline'=>$p[6],'cover_image'=>$images[$i],'body_content'=>'<p>Designed and delivered with a focus on clarity, durable materials, technical coordination and disciplined execution.</p>','is_featured'=>$i<4]); ProjectMedia::create(['project_id'=>$x->id,'path'=>$images[$i],'type'=>'image','sort_order'=>1,'alt_text'=>$x->title]); }
 $nc=[]; foreach(['Construction Technology','Design Trends','Feng Shui & Space','Corporate Updates'] as $name){$nc[$name]=PostCategory::create(['name'=>$name,'slug'=>str($name)->slug()]);}
 $posts=[['BIM coordination: turning design intent into buildable reality','Construction Technology'],['Material honesty and the new industrial aesthetic','Design Trends'],['Designing daylight, airflow and calm interiors','Feng Shui & Space'],['Building safer sites through practical systems','Corporate Updates']]; foreach($posts as $i=>$p){Post::create(['category_id'=>$nc[$p[1]]->id,'title'=>$p[0],'slug'=>str($p[0])->slug(),'excerpt'=>'A practical perspective from our design and engineering team.','content'=>'<p>Strong projects are built from clear decisions, coordinated information and a disciplined process from concept through handover.</p><p>Our teams bring architecture, engineering, procurement and site execution together around measurable outcomes.</p>','thumbnail'=>$images[$i+1],'author_name'=>'Architecture Studio','author_role'=>'Design & Engineering','published_at'=>now()->subDays($i+2)]);}
 foreach([['Senior Architect','Architecture','Da Nang','Negotiable'],['Site Supervisor','Construction','Da Nang','Negotiable'],['Quantity Surveyor','Commercial','Da Nang','Negotiable'],['BIM Modeler','BIM / VDC','Da Nang','Negotiable']] as $j){Career::create(['job_title'=>$j[0],'department'=>$j[1],'location'=>$j[2],'salary_range'=>$j[3],'description'=>'Coordinate multidisciplinary work, maintain technical standards and support project delivery.','deadline'=>now()->addMonths(2),'status'=>'open']);}
 }}
